/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตรวจว่าระบบพร้อมใช้งาน (public) */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เริ่มทุกการเข้าสู่ระบบ — สร้าง state แล้วส่งไปเว็บ Core Hub /sso/authorize (ไม่มีหน้าฟอร์ม) */
        get: operations["Sso_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Central SSO callback — ผลตามข้อ 5.1 ของสัญญา */
        get: operations["Sso_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ออกจากระบบทั้งระบบ — ลบคุกกี้ของระบบนี้ทั้งสอง แล้วไปหน้า /logout ของ Core Hub */
        post: operations["Sso_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตัวตนของผู้ใช้ปัจจุบัน */
        get: operations["Me_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * สร้างตัวละครของผู้ใช้ปัจจุบัน (หนึ่งคนมีได้ตัวเดียว)
         * @description ชื่อในเกมคือ personCode (รหัสนักศึกษา/บุคลากร) ที่อ่านจาก Core Hub GET /people/me ด้วย token ของผู้ใช้ตอนสร้าง · บัญชีที่ไม่มีรหัสได้ 400 VALIDATION_ERROR (details ขึ้นต้นด้วย displayName) ให้ส่ง displayName มาใหม่ · Core Hub ล่มหรือจำกัดอัตรา → 503 พร้อม Retry-After
         */
        post: operations["Characters_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตัวละครของผู้ใช้ปัจจุบัน */
        get: operations["Characters_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** เลือกอาชีพ — ครั้งเดียว หลังผ่านชั้น 1 */
        patch: operations["Characters_update"];
        trace?: never;
    };
    "/api/v1/characters/current/class-trials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ตัวอย่างการรบของอาชีพก่อนเลือก — ตัวละครจริง เวฟเดียวกันทุกอาชีพ ไม่ได้รางวัลและไม่บันทึก */
        post: operations["Characters_classTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** โปรแกรมปัจจุบัน + ไวยากรณ์และสกิลที่ใช้ได้ */
        get: operations["Programs_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * บันทึกโปรแกรม — ไม่ผ่าน parse/validate ตอบ 400 VALIDATION_ERROR
         * @description details แต่ละตัวเป็น "<บรรทัด>:<คอลัมน์>:<ชื่อข้อผิดพลาด>:<ข้อความไทย>"
         */
        patch: operations["Programs_update"];
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ไอเทมทั้งหมดในกระเป๋า เรียงตามลำดับที่ได้มา · q ค้นในชื่อไอเทม */
        get: operations["Items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ย่อยไอเทมเป็นวัสดุ */
        delete: operations["Items_remove"];
        options?: never;
        head?: never;
        /** สวมหรือถอดไอเทม */
        patch: operations["Items_update"];
        trace?: never;
    };
    "/api/v1/item-upgrades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ตีบวกไอเทม +1 ด้วยทองและวัสดุ */
        post: operations["ItemUpgrades_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ภูมิภาคบนแผนที่ + ความคืบหน้าของผู้ใช้ + จำนวนผู้เล่นในโซน */
        get: operations["Regions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/region-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** เข้าโซน — คืนคำประกาศของรอบ (EX · คู่ดวล · ล็อกเลเวล) */
        post: operations["RegionRuns_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/region-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ออกจากโซน */
        delete: operations["RegionRuns_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/battles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ประวัติการรบแบบย่อ ล่าสุดก่อน · q ค้นในชื่อสถานที่ (หอคอย หรือชื่อภูมิภาค) */
        get: operations["Battles_list"];
        put?: never;
        /** รบ — ท้าทายหอคอย (towerFloor) หรือรบรอบในภูมิภาค (regionRunId) */
        post: operations["Battles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tower-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ความคืบหน้าของหอคอย */
        get: operations["TowerProgress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ชื่อไทยของสกิล/ไอเทม/คุณสมบัติ + ข้อมูลอาชีพ */
        get: operations["GameData_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** โจทย์ทั้งหมด ล่าสุดก่อน · q ค้นในชื่อและคำอธิบาย */
        get: operations["Challenges_list"];
        put?: never;
        /** สร้างโจทย์ (ผู้สอน) */
        post: operations["Challenges_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** โจทย์หนึ่งข้อ */
        get: operations["Challenges_get"];
        put?: never;
        post?: never;
        /** ลบโจทย์ (เจ้าของหรือผู้ดูแล) */
        delete: operations["Challenges_remove"];
        options?: never;
        head?: never;
        /** แก้โจทย์ (เจ้าของหรือผู้ดูแล) */
        patch: operations["Challenges_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @enum {string} */
            status: "ok";
            /** @example csmju-gamification-knowledge */
            service: string;
        };
        PageMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        ErrorDetailDto: {
            /** @enum {string} */
            code: "BAD_REQUEST" | "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "TOO_MANY_REQUESTS" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE";
            message: string;
            /** @description ใช้กับ VALIDATION_ERROR */
            details?: string[];
        };
        ErrorEnvelopeDto: {
            /** @enum {boolean} */
            success: false;
            error: components["schemas"]["ErrorDetailDto"];
        };
        SessionInfoDto: {
            /**
             * Format: date-time
             * @description คำนวณจาก exp ของ token (ISO 8601)
             */
            expiresAt: string;
        };
        MeDto: {
            /** @description ค่า sub จาก Core Hub token (Global Identity) */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            coreRole: "student" | "alumni" | "staff" | "lecturer" | "guest" | "admin";
            /** @enum {string} */
            subsystemRole: "PLAYER" | "INSTRUCTOR" | "ADMIN";
            /** @description permission ของ role นี้ในระบบ Code Tower */
            permissions: string[];
            session: components["schemas"]["SessionInfoDto"];
        };
        ProficiencyTripleDto: {
            str: number;
            int: number;
            vit: number;
        };
        ProficiencyDto: {
            /** @description งานดิบตั้งแต่เลเวลที่แล้ว */
            work: components["schemas"]["ProficiencyTripleDto"];
            /** @description สัดส่วนหลังถ่วงน้ำหนัก รวม 1.0 */
            share: components["schemas"]["ProficiencyTripleDto"];
            /** @description ถ้าเลเวลอัพตอนนี้จะได้ช่องละกี่แต้ม */
            projectedPoints: components["schemas"]["ProficiencyTripleDto"];
            pointsPerLevel: number;
            usingClassDefault: boolean;
        };
        StatsDto: {
            str: number;
            int: number;
            vit: number;
            agi: number;
            luk: number;
        };
        DerivedStatsDto: {
            maxHp: number;
            maxMp: number;
            /** @description พลังโจมตีกายภาพ */
            atk: number;
            /** @description พลังเวท */
            matk: number;
            def: number;
            mdef: number;
            speed: number;
            /** @description 0..1 */
            critRate: number;
            /** @description ตัวคูณ เช่น 1.5 */
            critDmg: number;
            /** @description 0..1 */
            evasion: number;
            /** @description 0..1 */
            dropBonus: number;
        };
        StatValueDto: {
            stat: string;
            value: number;
        };
        ItemDto: {
            /** Format: uuid */
            id: string;
            baseId: string;
            /** @enum {string} */
            slot: "weapon" | "armor" | "helmet" | "accessory";
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
            upgradeLevel: number;
            droppedFloor: number;
            /** @description คุณสมบัติเสริม */
            affixes: components["schemas"]["StatValueDto"][];
            nameTh: string;
            /** @description ค่าหลักหลังตีบวกแล้ว */
            mainStat: components["schemas"]["StatValueDto"];
            equipped: boolean;
        };
        EquipmentDto: {
            weapon: components["schemas"]["ItemDto"] | null;
            armor: components["schemas"]["ItemDto"] | null;
            helmet: components["schemas"]["ItemDto"] | null;
            accessory: components["schemas"]["ItemDto"] | null;
        };
        SkillSummaryDto: {
            id: string;
            nameTh: string;
            unlockLevel: number;
            mpCost: number;
            /** @enum {string} */
            kind: "physical" | "magic" | "heal" | "shield" | "taunt";
            aoe: boolean;
            /** @description สกิลประจำภูมิภาค: id ของภูมิภาคที่พิสูจน์แล้วได้สกิลนี้ (ไม่มี = สกิลอาชีพตามเลเวล) */
            region?: string;
        };
        CharacterDto: {
            /** Format: uuid */
            id: string;
            /** @description ชื่อที่ผู้เล่นคนอื่นเห็น — รหัสนักศึกษา/บุคลากรจาก Core Hub หรือชื่อสำรองของบัญชีที่ไม่มีรหัส */
            displayName: string;
            /** @enum {string} */
            classId: "novice" | "warrior" | "mage" | "guardian";
            level: number;
            exp: number;
            expToNext: number;
            proficiency: components["schemas"]["ProficiencyDto"];
            stats: components["schemas"]["StatsDto"];
            /** @description ค่าที่คำนวณแล้ว (maxHp, atk, …) */
            derived: components["schemas"]["DerivedStatsDto"];
            gold: number;
            materials: number;
            equipment: components["schemas"]["EquipmentDto"];
            skills: components["schemas"]["SkillSummaryDto"][];
            highestFloorCleared: number;
        };
        CreateCharacterDto: {
            /**
             * @description ไม่ต้องส่งตามปกติ — ชื่อในเกมคือรหัสนักศึกษา/บุคลากรจาก Core Hub · ส่งเฉพาะเมื่อได้ 400 ที่บอกว่าบัญชีนี้ไม่มีรหัส (ถ้ามีรหัส ค่านี้ถูกละไว้)
             * @example นักสู้หมายเลข1
             */
            displayName?: string;
        };
        UpdateCharacterDto: {
            /**
             * @description เลือกอาชีพได้ครั้งเดียว หลังผ่านชั้น 1
             * @enum {string}
             */
            classId: "warrior" | "mage" | "guardian";
        };
        CombatTargetDto: {
            id: string;
            name: string;
            damage?: number;
            heal?: number;
            shield?: number;
            crit?: boolean;
            evaded?: boolean;
            killed?: boolean;
            hpAfter: number;
        };
        CombatEventDto: {
            turn: number;
            wave: number;
            actorId: string;
            actorName: string;
            /**
             * @description wait = เทิร์นที่โปรแกรมสั่ง wait() — ไม่มีเป้าหมาย มีแค่ mpAfter ที่ฟื้นขึ้น
             * @enum {string}
             */
            action: "attack" | "skill" | "defend" | "wait";
            skillId?: string;
            targets: components["schemas"]["CombatTargetDto"][];
            /** @enum {string} */
            note?: "wave_start" | "wave_clear" | "defend" | "windup";
            /** @description บรรทัดในโปรแกรม BloxCode ที่ตัดสินใจเทิร์นนี้ (0 = การกระทำสำรอง) */
            line?: number;
            /** @description คำเตือนตอนรันโปรแกรม */
            codeWarnings?: string[];
            /** @description MP ของผู้ลงมือหลังจบเทิร์นนี้ (หักค่าร่ายและฟื้นตอนจบเทิร์นแล้ว) — ไม่มีใน event ของระบบ */
            mpAfter?: number;
        };
        ClassTrialResultDto: {
            victory: boolean;
            wavesCleared: number;
            events: components["schemas"]["CombatEventDto"][];
        };
        ClassTrialSummaryDto: {
            /** @description จำนวนเทิร์นที่ตัวละครได้ลงมือ */
            turns: number;
            /** @description ร่ายสกิลกี่ครั้ง */
            skillCasts: number;
            damageDealt: number;
            damageTaken: number;
            /** @description เลือดที่เหลือตอนจบ (% ของหลอด) */
            hpLeftPct: number;
        };
        ClassTrialDto: {
            /** @enum {string} */
            classId: "warrior" | "mage" | "guardian";
            /** @description เลเวลของตัวละครที่ใช้ (เลเวลปัจจุบัน) */
            level: number;
            /** @description ชั้นของเวฟตัวอย่าง (ชั้นที่ผ่านล่าสุด อย่างน้อย 1) */
            floor: number;
            /** @description จำนวนเวฟของตัวอย่าง */
            waves: number;
            /** @description โปรแกรมตัวอย่าง — เขียนด้วยไวยากรณ์ที่ใช้ได้ตั้งแต่ผ่านชั้น 1 */
            program: string;
            /** @description สกิลที่โปรแกรมตัวอย่างเรียก (ที่ปลดแล้วที่เลเวลนี้) */
            skills: string[];
            maxHp: number;
            maxMp: number;
            result: components["schemas"]["ClassTrialResultDto"];
            summary: components["schemas"]["ClassTrialSummaryDto"];
        };
        CreateClassTrialDto: {
            /**
             * @description อาชีพที่อยากเห็นตัวอย่าง
             * @enum {string}
             */
            classId: "warrior" | "mage" | "guardian";
        };
        ProgramSkillDto: {
            id: string;
            nameTh: string;
            mpCost: number;
            aoe: boolean;
        };
        ProgramDto: {
            source: string;
            /** @description ไวยากรณ์ที่ปลดล็อกแล้ว */
            unlockedFeatures: string[];
            availableSkills: components["schemas"]["ProgramSkillDto"][];
            highestFloorCleared: number;
        };
        UpdateProgramDto: {
            /** @description โปรแกรม BloxCode (Python subset) — ต้องมี def turn(): */
            source: string;
        };
        UpdateItemDto: {
            /** @description true = สวมใส่ (ของเดิมในช่องเดียวกันถูกถอดให้) · false = ถอด */
            equipped: boolean;
        };
        SalvagedItemDto: {
            /** Format: uuid */
            id: string;
            /** @enum {boolean} */
            deleted: true;
            /** @description วัสดุที่ได้จากการย่อยชิ้นนี้ */
            materialsGained: number;
            /** @description วัสดุคงเหลือหลังย่อย */
            materials: number;
        };
        ItemUpgradeDto: {
            item: components["schemas"]["ItemDto"];
            goldSpent: number;
            materialsSpent: number;
            /** @description ทองคงเหลือ */
            gold: number;
            /** @description วัสดุคงเหลือ */
            materials: number;
        };
        CreateItemUpgradeDto: {
            /** Format: uuid */
            itemId: string;
        };
        HotspotDto: {
            x: number;
            y: number;
            /** @description รัศมี (สัดส่วนของความกว้าง) */
            r: number;
        };
        RegionSkillDto: {
            id: string;
            nameTh: string;
            /** @enum {string} */
            kind: "physical" | "magic" | "heal" | "shield" | "taunt";
            mpCost: number;
            aoe: boolean;
        };
        RegionProofInfoDto: {
            /** @description เงื่อนไขที่ต้องทำให้ครบในการรบครั้งเดียว (ข้อแรก = ชนะรอบลึกสุด) */
            requirementsTh: string[];
            /** @description ตัวละครนี้พิสูจน์ภูมิภาคนี้แล้ว */
            proved: boolean;
            /** @description สกิลที่จะได้/ได้แล้วสำหรับอาชีพของคุณ (null = ผู้ฝึกหัด ยังไม่มีอาชีพ) */
            skill: components["schemas"]["RegionSkillDto"] | null;
        };
        RegionDto: {
            id: string;
            nameTh: string;
            floorBase: number;
            /** @description จำนวนรอบของโซน (0 = เมือง ไม่มีการรบ) */
            depths: number;
            floorRange: number[];
            lessonTh: string;
            eliteChance: number;
            hotspot: components["schemas"]["HotspotDto"];
            depthCleared: number;
            maxDepthAllowed: number;
            completed: boolean;
            unlocked: boolean;
            /** @description จำนวนผู้เล่นที่อยู่ในโซนนี้ตอนนี้ */
            playersHere: number;
            /** @description สกิลประจำภูมิภาค (null = หอคอย · เมือง ไม่มีสกิลให้พิสูจน์) */
            proof: components["schemas"]["RegionProofInfoDto"] | null;
        };
        EliteDto: {
            wave: number;
            archetypeId: string;
            nameTh: string;
        };
        DuelAnnounceDto: {
            displayName: string;
            classId: string;
            level: number;
            /** @description true = อยู่ในโซนตอนนี้จริง · false = สแนปช็อต */
            live: boolean;
        };
        LevelSyncDto: {
            level: number;
            realLevel: number;
            applies: boolean;
        };
        RegionRunDto: {
            /** Format: uuid */
            id: string;
            regionId: string;
            depth: number;
            floor: number;
            nameTh: string;
            lessonTh: string;
            elite?: components["schemas"]["EliteDto"] | null;
            duel?: components["schemas"]["DuelAnnounceDto"] | null;
            sync?: components["schemas"]["LevelSyncDto"] | null;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateRegionRunDto: {
            /**
             * @description id ของภูมิภาค (จาก GET /api/v1/regions)
             * @example frostland
             */
            regionId: string;
            /** @description รอบที่เท่าไรของโซน (เข้าได้ถึง maxDepthAllowed) */
            depth: number;
        };
        DeletedDto: {
            /** Format: uuid */
            id: string;
            /** @enum {boolean} */
            deleted: true;
        };
        BattleDropsDto: {
            gold: number;
            materials: number;
            items: components["schemas"]["ItemDto"][];
        };
        BattleResultDto: {
            victory: boolean;
            wavesCleared: number;
            /** @description บันทึกการรบ (CombatEvent ของ engine) */
            events: components["schemas"]["CombatEventDto"][];
            drops: components["schemas"]["BattleDropsDto"];
            expGained: number;
            seed: number;
        };
        DuelBlockDto: {
            opponent: components["schemas"]["DuelAnnounceDto"];
            events: components["schemas"]["CombatEventDto"][];
            won: boolean;
            byTimeout: boolean;
            rounds: number;
            /** @description โปรแกรมของคู่ดวล — ฝ่ายแพ้เปิดดูได้ (รอบ 2W §5.4) */
            opponentProgram: string;
        };
        ProofCheckDto: {
            /** @description รหัสคงที่ของเงื่อนไข เช่น deepest_win · handled · hp_floor */
            code: string;
            /** @description ข้อความพร้อมตัวเลขของการรบครั้งนี้ */
            textTh: string;
            ok: boolean;
        };
        RegionProofDto: {
            regionId: string;
            /** @description การรบนี้นับไหม — ต้องเป็นรอบลึกสุดของภูมิภาค */
            eligible: boolean;
            /** @description นับ + ชนะ + ผ่านทุกเงื่อนไข */
            passed: boolean;
            /** @description พิสูจน์สำเร็จครั้งแรกในการรบนี้ (ได้สกิลตอนนี้) */
            newlyProved: boolean;
            checks: components["schemas"]["ProofCheckDto"][];
            /** @description สกิลของภูมิภาคนี้สำหรับอาชีพของคุณ (null = ผู้ฝึกหัด) */
            skill: components["schemas"]["RegionSkillDto"] | null;
        };
        PreviousAttemptDto: {
            victory: boolean;
            wavesCleared: number;
            /** Format: date-time */
            createdAt: string;
        };
        BattleAttemptDto: {
            /** @description ครั้งที่ของการรบที่จุดนี้ (1 = ครั้งแรก) */
            attemptNo: number;
            /** @description ครั้งแรกที่จุดนี้ — หน้าเว็บให้ดูฉากจนจบก่อน */
            firstAttempt: boolean;
            /** @description ผลครั้งก่อนที่จุดนี้ (null = ไม่เคยรบ) */
            previous: components["schemas"]["PreviousAttemptDto"] | null;
        };
        BattleOutcomeDto: {
            /**
             * Format: uuid
             * @description id ของบันทึกการรบแบบย่อ (GET /api/v1/battles)
             */
            id: string;
            result: components["schemas"]["BattleResultDto"];
            /** @description มีเฉพาะการรบในภูมิภาค */
            announce?: components["schemas"]["RegionRunDto"];
            /** @description มีเฉพาะการรบในภูมิภาค */
            duel?: components["schemas"]["DuelBlockDto"] | null;
            /** @description มีเฉพาะการรบในภูมิภาค · null = ภูมิภาคนี้ไม่มีสกิลให้พิสูจน์ */
            proof?: components["schemas"]["RegionProofDto"] | null;
            /** @description ตัวละครหลังบันทึกผลแล้ว */
            character: components["schemas"]["CharacterDto"];
            leveledUp: boolean;
            newLevel?: number;
            /** @description สเตตัสที่ได้จากการเลเวลอัพรอบนี้ */
            statsGained?: components["schemas"]["StatsDto"];
            attempt: components["schemas"]["BattleAttemptDto"];
        };
        CreateBattleDto: {
            /** @description ชั้นของหอคอยที่จะท้าทาย */
            towerFloor?: number;
            /**
             * Format: uuid
             * @description id ของรอบจาก POST /api/v1/region-runs
             */
            regionRunId?: string;
        };
        BattleSummaryDto: {
            /** Format: uuid */
            id: string;
            regionId: string;
            depth: number;
            floor: number;
            victory: boolean;
            wavesCleared: number;
            expGained: number;
            goldGained: number;
            /** Format: date-time */
            createdAt: string;
        };
        TowerProgressDto: {
            /** @description ชั้นสูงสุดของหอคอยที่ผ่านแล้ว (ใบคะแนนของหอคอยเอง) */
            highestFloorCleared: number;
            maxFloor: number;
            /** @description ความยากสูงสุดที่ผ่านแล้ว "ที่ไหนก็ได้" — ตัวปลดล็อกภูมิภาคและไวยากรณ์ */
            globalHighestFloor: number;
        };
        ClassInfoDto: {
            nameTh: string;
            growthHint: string;
            baseStats: components["schemas"]["StatsDto"];
        };
        SkillDefDto: {
            id: string;
            name: string;
            nameTh: string;
            /** @enum {string} */
            classId: "novice" | "warrior" | "mage" | "guardian" | "monster";
            /** @enum {string} */
            kind: "physical" | "magic" | "heal" | "shield" | "taunt";
            /** @description physical/magic = % ของ atk/matk (100 = 1 เท่า) · heal = % ของเลือดสูงสุดของเป้า · shield = % ของเลือดสูงสุดของผู้ร่าย · taunt ไม่ใช้ */
            power: number;
            mpCost: number;
            aoe: boolean;
            unlockLevel: number;
            /** @description คำอธิบายสำหรับผู้เล่น (มีเฉพาะสกิลของอาชีพ) */
            descTh?: string;
            /** @description ชื่อแอนิเมชันเอฟเฟกต์ที่ฉากรบใช้วาด */
            animation?: string;
            /** @description สกิลประจำภูมิภาค: ได้เมื่อพิสูจน์บทเรียนของภูมิภาคนี้ ไม่ได้ตามเลเวล (unlockLevel ไม่มีความหมาย) */
            region?: string;
        };
        RegionNameDto: {
            id: string;
            nameTh: string;
            /** @description จำนวนรอบของโซน (0 = เมือง ไม่มีการรบ) */
            depths: number;
        };
        GameDataDto: {
            /** @description สกิลของทุกอาชีพและของมอนสเตอร์ */
            skills: components["schemas"]["SkillDefDto"][];
            affixNames: {
                [key: string]: string;
            };
            rarities: string[];
            baseItemNames: {
                [key: string]: string;
            };
            classes: {
                [key: string]: components["schemas"]["ClassInfoDto"];
            };
            /** @description ภูมิภาคทั้งหมดบนแผนที่ (id + ชื่อไทย) — ใช้กับฟอร์มโจทย์และประวัติการรบ */
            regions: components["schemas"]["RegionNameDto"][];
        };
        ChallengeDto: {
            /** Format: uuid */
            id: string;
            /** @description core_user_id ของผู้สร้าง */
            coreUserId: string;
            title: string;
            description: string;
            starterSource: string;
            /** @description ภูมิภาคที่ผูก · null = ไม่ผูก */
            regionId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateChallengeDto: {
            /** @example ตั้งการ์ดเมื่อถูกหมายหัว */
            title: string;
            description?: string;
            /** @description โปรแกรมตั้งต้นให้ผู้เล่น — ต้อง parse ผ่าน · เว้นไว้ = โปรแกรมพื้นฐาน */
            starterSource?: string;
            /**
             * @description ภูมิภาคที่โจทย์นี้ผูกด้วย (ถ้ามี)
             * @example frostland
             */
            regionId?: string | null;
        };
        UpdateChallengeDto: {
            title?: string;
            description?: string;
            starterSource?: string;
            /** @description null = เลิกผูกกับภูมิภาค */
            regionId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["HealthDto"];
                    };
                };
            };
        };
    };
    Sso_login: {
        parameters: {
            query?: {
                /** @description path ในระบบนี้ที่จะกลับไปหลัง login · ไม่ผ่านกฎใช้หน้าแรก */
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ไป {CORE_HUB_WEB_URL}/sso/authorize?subsystem=…&state=… พร้อมคุกกี้ state */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Sso_callback: {
        parameters: {
            query: {
                state?: string;
                expires_in?: string;
                token_type?: "Bearer";
                access_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ — ตั้งคุกกี้ session แล้วไปหน้า next · หรือไม่มี state (เริ่มจาก Core Hub) — ทิ้ง token แล้วไป /auth/login */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Sso_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ไป {CORE_HUB_WEB_URL}/logout */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Me_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MeDto"];
                    };
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Characters_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterDto"];
            };
        };
        responses: {
            /** @description สร้างแล้ว */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CharacterDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description SERVICE_UNAVAILABLE — ระบบที่พึ่ง (Core Hub) ไม่พร้อมชั่วคราว · มี header Retry-After */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Characters_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CharacterDto"];
                    };
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Characters_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCharacterDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["CharacterDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Characters_classTrial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClassTrialDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ClassTrialDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Programs_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProgramDto"];
                    };
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Programs_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProgramDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProgramDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Items_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description คำค้นหา ไม่สนตัวพิมพ์เล็ก/ใหญ่ · ว่าง = ทั้งหมด */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ItemDto"][];
                        meta: components["schemas"]["PageMetaDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Items_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SalvagedItemDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Items_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ItemDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    ItemUpgrades_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemUpgradeDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ItemUpgradeDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Regions_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RegionDto"][];
                        meta: components["schemas"]["PageMetaDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    RegionRuns_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegionRunDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["RegionRunDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    RegionRuns_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Battles_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description คำค้นหา ไม่สนตัวพิมพ์เล็ก/ใหญ่ · ว่าง = ทั้งหมด */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BattleSummaryDto"][];
                        meta: components["schemas"]["PageMetaDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Battles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBattleDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["BattleOutcomeDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description CONFLICT — สถานะปัจจุบันไม่อนุญาต */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    TowerProgress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["TowerProgressDto"];
                    };
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    GameData_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["GameDataDto"];
                    };
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Challenges_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description คำค้นหา ไม่สนตัวพิมพ์เล็ก/ใหญ่ · ว่าง = ทั้งหมด */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChallengeDto"][];
                        meta: components["schemas"]["PageMetaDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Challenges_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChallengeDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChallengeDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Challenges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChallengeDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Challenges_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
    Challenges_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateChallengeDto"];
            };
        };
        responses: {
            /** @description สำเร็จ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ChallengeDto"];
                    };
                };
            };
            /** @description BAD_REQUEST หรือ VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description UNAUTHORIZED — ไม่มี token หรือ token ใช้ไม่ได้ */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description FORBIDDEN — สิทธิ์ไม่พอ */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelopeDto"];
                };
            };
        };
    };
}
